(function () {
  const countries = [
    { name: "Czech Republic", code: "CZ", lat: 49.8, lng: 15.5, flag: "CZ" },
    { name: "Germany", code: "DE", lat: 51.2, lng: 10.4, flag: "DE" },
    { name: "France", code: "FR", lat: 46.2, lng: 2.2, flag: "FR" },
    { name: "Spain", code: "ES", lat: 40.4, lng: -3.7, flag: "ES" },
    { name: "Italy", code: "IT", lat: 41.9, lng: 12.6, flag: "IT" },
    { name: "Poland", code: "PL", lat: 52.1, lng: 19.1, flag: "PL" },
    { name: "United Kingdom", code: "GB", lat: 54.2, lng: -2.4, flag: "GB" },
    { name: "United States", code: "US", lat: 39.8, lng: -98.5, flag: "US" },
    { name: "Canada", code: "CA", lat: 56.1, lng: -106.3, flag: "CA" },
    { name: "Brazil", code: "BR", lat: -14.2, lng: -51.9, flag: "BR" },
    { name: "Japan", code: "JP", lat: 36.2, lng: 138.2, flag: "JP" },
    { name: "South Korea", code: "KR", lat: 36.5, lng: 127.8, flag: "KR" },
    { name: "Australia", code: "AU", lat: -25.2, lng: 133.7, flag: "AU" },
    { name: "South Africa", code: "ZA", lat: -30.6, lng: 22.9, flag: "ZA" },
    { name: "Norway", code: "NO", lat: 60.5, lng: 8.4, flag: "NO" },
    { name: "Sweden", code: "SE", lat: 60.1, lng: 18.6, flag: "SE" },
    { name: "Finland", code: "FI", lat: 64.2, lng: 26.0, flag: "FI" },
    { name: "Mexico", code: "MX", lat: 23.6, lng: -102.5, flag: "MX" },
    { name: "Argentina", code: "AR", lat: -38.4, lng: -63.6, flag: "AR" },
    { name: "New Zealand", code: "NZ", lat: -41.8, lng: 172.9, flag: "NZ" }
  ];

  const locations = [
    {
      id: "cz-prague-suburb",
      country: "Czech Republic",
      countryCode: "CZ",
      lat: 50.0755,
      lng: 14.4378,
      city: "Prague",
      region: "Bohemia",
      panoramaImage: "",
      difficulty: "Easy",
      mapPool: ["World", "Europe", "City Mix"],
      style: "europe",
      clues: ["blue road signs", "Czech diacritics", ".cz domain", "red roof village houses", "right-side driving"]
    },
    {
      id: "de-bavaria-road",
      country: "Germany",
      countryCode: "DE",
      lat: 48.1351,
      lng: 11.582,
      city: "Munich",
      region: "Bavaria",
      panoramaImage: "",
      difficulty: "Easy",
      mapPool: ["World", "Europe", "City Mix"],
      style: "europe",
      clues: ["Autobahn signs", "umlauts", "clean lane markings", "red-bordered signs", ".de domain"]
    },
    {
      id: "fr-provence-lane",
      country: "France",
      countryCode: "FR",
      lat: 43.9352,
      lng: 6.0679,
      city: "Provence",
      region: "Alpes-de-Haute-Provence",
      panoramaImage: "",
      difficulty: "Medium",
      mapPool: ["World", "Europe"],
      style: "mediterranean",
      clues: ["French village signs", "plane trees", "D-road marker", "stone houses", ".fr domain"]
    },
    {
      id: "es-andalusia",
      country: "Spain",
      countryCode: "ES",
      lat: 37.3891,
      lng: -5.9845,
      city: "Seville",
      region: "Andalusia",
      panoramaImage: "",
      difficulty: "Medium",
      mapPool: ["World", "Europe", "City Mix"],
      style: "dry",
      clues: ["Spanish language", "whitewashed walls", "dry heat", "red-yellow road signs", ".es domain"]
    },
    {
      id: "it-tuscany",
      country: "Italy",
      countryCode: "IT",
      lat: 43.7711,
      lng: 11.2486,
      city: "Florence",
      region: "Tuscany",
      panoramaImage: "",
      difficulty: "Medium",
      mapPool: ["World", "Europe", "City Mix"],
      style: "mediterranean",
      clues: ["Italian words", "cypress trees", "narrow roads", "terra-cotta buildings", ".it domain"]
    },
    {
      id: "pl-krakow",
      country: "Poland",
      countryCode: "PL",
      lat: 50.0647,
      lng: 19.945,
      city: "Krakow",
      region: "Lesser Poland",
      panoramaImage: "",
      difficulty: "Easy",
      mapPool: ["World", "Europe", "City Mix"],
      style: "europe",
      clues: ["Polish letters", "yellow pedestrian signs", "EU plates", "tram wires", ".pl domain"]
    },
    {
      id: "gb-yorkshire",
      country: "United Kingdom",
      countryCode: "GB",
      lat: 53.9583,
      lng: -1.0803,
      city: "York",
      region: "Yorkshire",
      panoramaImage: "",
      difficulty: "Easy",
      mapPool: ["World", "Europe", "City Mix"],
      style: "uk",
      clues: ["left-side driving", "yellow rear plates", "English road names", "stone walls", ".uk domain"]
    },
    {
      id: "us-arizona",
      country: "United States",
      countryCode: "US",
      lat: 34.0489,
      lng: -111.0937,
      city: "Flagstaff",
      region: "Arizona",
      panoramaImage: "",
      difficulty: "Medium",
      mapPool: ["World", "City Mix"],
      style: "desert",
      clues: ["wide roads", "US route shields", "miles", "desert vegetation", "yellow center lines"]
    },
    {
      id: "ca-banff",
      country: "Canada",
      countryCode: "CA",
      lat: 51.1784,
      lng: -115.5708,
      city: "Banff",
      region: "Alberta",
      panoramaImage: "",
      difficulty: "Medium",
      mapPool: ["World"],
      style: "mountain",
      clues: ["Trans-Canada Highway", "mountain parks", "English and French labels", ".ca domain", "wildlife signs"]
    },
    {
      id: "br-rio",
      country: "Brazil",
      countryCode: "BR",
      lat: -22.9068,
      lng: -43.1729,
      city: "Rio de Janeiro",
      region: "Rio de Janeiro",
      panoramaImage: "",
      difficulty: "Medium",
      mapPool: ["World", "City Mix"],
      style: "tropical",
      clues: ["Portuguese language", "PARE signs", "tropical hills", ".br domain", "colorful storefronts"]
    },
    {
      id: "jp-tokyo",
      country: "Japan",
      countryCode: "JP",
      lat: 35.6762,
      lng: 139.6503,
      city: "Tokyo",
      region: "Kanto",
      panoramaImage: "",
      difficulty: "Easy",
      mapPool: ["World", "City Mix"],
      style: "urban",
      clues: ["Japanese script", "left-side driving", "dense overhead cables", "vending machines", "compact streets"]
    },
    {
      id: "kr-seoul",
      country: "South Korea",
      countryCode: "KR",
      lat: 37.5665,
      lng: 126.978,
      city: "Seoul",
      region: "Capital Area",
      panoramaImage: "",
      difficulty: "Medium",
      mapPool: ["World", "City Mix"],
      style: "urban",
      clues: ["Hangul signs", "wide avenues", "mountain skyline", "Korean street plates", ".kr domain"]
    },
    {
      id: "au-outback",
      country: "Australia",
      countryCode: "AU",
      lat: -25.2744,
      lng: 133.7751,
      city: "Alice Springs",
      region: "Northern Territory",
      panoramaImage: "",
      difficulty: "Medium",
      mapPool: ["World"],
      style: "desert",
      clues: ["red dirt", "left-side driving", "road train warning", "long empty roads", "yellow wildlife signs"]
    },
    {
      id: "za-cape-town",
      country: "South Africa",
      countryCode: "ZA",
      lat: -33.9249,
      lng: 18.4241,
      city: "Cape Town",
      region: "Western Cape",
      panoramaImage: "",
      difficulty: "Hard",
      mapPool: ["World", "City Mix"],
      style: "coastal",
      clues: ["left-side driving", "Table Mountain silhouette", "English road signs", ".za domain", "dry coastal plants"]
    },
    {
      id: "no-fjord",
      country: "Norway",
      countryCode: "NO",
      lat: 60.3913,
      lng: 5.3221,
      city: "Bergen",
      region: "Vestland",
      panoramaImage: "",
      difficulty: "Medium",
      mapPool: ["World", "Europe"],
      style: "nordic",
      clues: ["fjord landscape", "Norwegian letters", "tunnel signs", "red cabins", ".no domain"]
    },
    {
      id: "se-stockholm",
      country: "Sweden",
      countryCode: "SE",
      lat: 59.3293,
      lng: 18.0686,
      city: "Stockholm",
      region: "Svealand",
      panoramaImage: "",
      difficulty: "Medium",
      mapPool: ["World", "Europe", "City Mix"],
      style: "nordic",
      clues: ["Swedish signs", "blue-yellow colors", "clean urban design", ".se domain", "Nordic bike lanes"]
    },
    {
      id: "fi-lapland",
      country: "Finland",
      countryCode: "FI",
      lat: 66.5039,
      lng: 25.7294,
      city: "Rovaniemi",
      region: "Lapland",
      panoramaImage: "",
      difficulty: "Hard",
      mapPool: ["World", "Europe"],
      style: "snow",
      clues: ["Finnish words", "snowy shoulders", "pine forest", ".fi domain", "reindeer warning signs"]
    },
    {
      id: "mx-oaxaca",
      country: "Mexico",
      countryCode: "MX",
      lat: 17.0732,
      lng: -96.7266,
      city: "Oaxaca",
      region: "Oaxaca",
      panoramaImage: "",
      difficulty: "Medium",
      mapPool: ["World", "City Mix"],
      style: "dry",
      clues: ["Spanish language", "topes signs", "colorful walls", ".mx domain", "warm highland light"]
    },
    {
      id: "ar-buenos-aires",
      country: "Argentina",
      countryCode: "AR",
      lat: -34.6037,
      lng: -58.3816,
      city: "Buenos Aires",
      region: "Buenos Aires",
      panoramaImage: "",
      difficulty: "Medium",
      mapPool: ["World", "City Mix"],
      style: "urban",
      clues: ["Spanish language", "wide avenues", "Argentinian plates", ".ar domain", "subte signs"]
    },
    {
      id: "nz-queenstown",
      country: "New Zealand",
      countryCode: "NZ",
      lat: -45.0312,
      lng: 168.6626,
      city: "Queenstown",
      region: "Otago",
      panoramaImage: "",
      difficulty: "Hard",
      mapPool: ["World"],
      style: "mountain",
      clues: ["left-side driving", "green highway shields", "alpine lakes", ".nz domain", "one-lane bridges"]
    }
  ];

  window.WorldGuessData = { countries, locations };
})();
